# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f73992ce13caaa0f3cc4fb75de142a1363a052cdd5662d9e08cfed3562277d99605bd51ea5e13f249ea17573556c61e1ccfc7ac10e1682c90d0a58f4e16135

test:
  secret_key_base: b10359a29a97c8cf370759ad2c32567e8e94ef160dcabcc4c0f1920ffbcb6909d10cd166cf90f29897a0edc6e057aded7672d9dcbd05b0d3fd00a099ac941723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
